# Welcome to Jekyll!
#

# Site settings
title: Braille Writer
description: |
  The Braille Writer, the future of inclusion.
owner: The Braille Writer # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: becahere@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rebecasarai.github.io/Braille-Writer" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/codelovr
  github: https://github.com/Rebecasarai
  linkedin-square: https://linkedin.com/in/rebeca-programming/
  facebook-official: https://facebook.com/Beca.Here
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
